import { marketCard } from './markets.js';
import { initChallengers } from './challengers.js';
const challengers = initChallengers();
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const api=async path=>{const r=await fetch(`/api${path}`,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmtOdds=v=>v===null||v===undefined||v===''?'—':String(v);const fmtNum=(v,suffix='')=>v===null||v===undefined||v===''?'—':`${v}${suffix}`;
const cardClass=p=>({RED:'red',ORANGE:'orange',BLUE:'blue',GRAY:'gray'}[p]||'gray');
const READ_NOTIFICATIONS_KEY='pbkReadNotificationsV1';let notificationPayload={items:[],summary:{}};

function signalCard(x){const odds=x.paper_user_odds??x.user_odds??'';const book=x.paper_user_book??x.user_book??'';return `<article class="card ${cardClass(x.priority)}" ${x.fixture_id?`data-fixture="${esc(x.fixture_id)}"`:''}><div><div class="eyebrow">${esc(x.rule||x.stage||x.league||'')}</div><div class="teams">${esc(x.home_team)} — ${esc(x.away_team)}</div><div class="meta">${esc(x.league||'')} · ${esc(x.kickoff_local||'')} ${x.context?`· ${esc(x.context)}`:''}${x.reason?`· ${esc(x.reason)}`:''}</div></div><div class="pick"><div class="selection">${esc(x.selection||x.market||'')}</div>${odds?`<div class="odds">${esc(fmtOdds(odds))}${book?` @ ${esc(book)}`:''}</div>`:''}</div></article>`}
function setList(id,items,renderer=signalCard){const el=$(id);el.innerHTML=items?.length?items.map(renderer).join(''):'<div class="empty">Сейчас ничего нет.</div>'}
function setHealthPill(status){const el=$('#health-pill');el.classList.remove('ok','warn','bad');const s=String(status||'UNKNOWN').toUpperCase();el.classList.add(s==='HEALTHY'||s==='OK'?'ok':s==='WARN'?'warn':'bad');el.querySelector('span:last-child').textContent=s}
function setDataSafety(level='',title='',text=''){const el=$('#data-safety-banner');if(!el)return;if(!level){el.hidden=true;el.className='safety-banner';return}el.hidden=false;el.className=`safety-banner ${level}`;$('#data-safety-title').textContent=title;$('#data-safety-text').textContent=text}
function dataAgeMinutes(v){if(!v)return null;const t=new Date(v).getTime();if(Number.isNaN(t))return null;return Math.max(0,(Date.now()-t)/60000)}
function applyFreshnessGuard(health,gov){const sys=gov?.system_health||{};const critical=Number(sys?.summary?.critical_issues||0);const warnings=Number(sys?.summary?.warnings||0);const apiCritical=String(health?.status||'').toUpperCase()==='CRITICAL'||String(sys?.status||'').toUpperCase()==='CRITICAL';const age=dataAgeMinutes(health?.db_built_at_utc);const ageLabel=age===null?'неизвестен':`${Math.round(age)} мин`;
  if(!navigator.onLine){setDataSafety('bad','Нет связи','Приложение не может подтвердить свежесть данных. Не используй коэффициенты или сигналы до восстановления соединения.');return age}
  if(apiCritical||critical>0||age!==null&&age>60){setDataSafety('bad','Данные нельзя считать актуальными',`Возраст Data Layer: ${ageLabel}. Есть critical/stale состояние — не используй коэффициенты и сигналы до восстановления Health.`);return age}
  if(warnings>0||age===null||age>20){setDataSafety('warn','Проверь свежесть данных',`Возраст Data Layer: ${ageLabel}${warnings?` · warnings: ${warnings}`:''}. Перед действием проверь Health и время последнего обновления.`);return age}
  setDataSafety();return age}

const first=v=>Array.isArray(v)&&v.length?v[0]:null;const last=v=>Array.isArray(v)&&v.length?v[v.length-1]:null;
function cleanPairs(obj,keys){return keys.map(([label,key])=>[label,obj?.[key]]).filter(([,v])=>v!==null&&v!==undefined&&v!=='')}
function section(title,html){return `<section class="detail-section"><h3>${esc(title)}</h3>${html}</section>`}
function pairGrid(pairs){return `<div class="detail-grid">${pairs.map(([k,v])=>`<div class="detail-row"><div class="eyebrow">${esc(k)}</div><b>${esc(v)}</b></div>`).join('')}</div>`}
function currentMarketRows(d){if(d.attention_card?.markets)return d.attention_card.markets.map(m=>`${m.text}${m.captured_at_utc?' · снимок '+m.captured_at_utc:''}`);const out=[];const tt=d.markets?.team_totals||{};const dnb=d.markets?.dnb||{};const dc=d.markets?.double_chance||{};const eh=d.markets?.european_handicap||{};
  const ttRows=tt.snapshots?.length?tt.snapshots:tt.openers||[];for(const r of ttRows.filter(x=>String(x.line)==='1.5').slice(-2)){const n=r.team_side==='H'?'1':'2';const over=r.user_over??r.open_user_over??r.open_b365_over??r.b365_over;const under=r.user_under??r.open_user_under??r.open_b365_under??r.b365_under;out.push(`ИТБ${n}(1.5) ${fmtOdds(over)} · ИТМ${n}(1.5) ${fmtOdds(under)}`)}
  const x=last(dc.snapshots)||last(dc.openers);if(x)out.push(`1Х ${fmtOdds(x.user_1x??x.open_b365_1x??x.b365_1x)} · Х2 ${fmtOdds(x.user_x2??x.open_b365_x2??x.b365_x2)} · 12 ${fmtOdds(x.user_12??x.open_b365_12??x.b365_12)}`);
  const y=last(dnb.snapshots)||last(dnb.openers);if(y)out.push(`Ф1(0) ${fmtOdds(y.user_f1_0??y.open_b365_f1_0??y.b365_f1_0)} · Ф2(0) ${fmtOdds(y.user_f2_0??y.open_b365_f2_0??y.b365_f2_0)}`);
  const z=(eh.snapshots?.length?eh.snapshots:eh.openers||[]).find(r=>String(r.home_handicap_line)==='1'||String(r.home_handicap_line)==='+1');if(z)out.push(`Европ. фора хозяев +1: П1 ${fmtOdds(z.user_home??z.open_b365_home??z.b365_home)} · Х ${fmtOdds(z.user_draw??z.open_b365_draw??z.b365_draw)} · П2 ${fmtOdds(z.user_away??z.open_b365_away??z.b365_away)}`);
  return out}

function renderMatchDetail(d){const i=d.identity||{};$('#detail-eyebrow').textContent=`${i.league||'Матч'} · ${i.kickoff_local||i.kickoff_utc||''}`;$('#detail-title').textContent=`${i.home_team||'—'} — ${i.away_team||'—'}`;let html='';
  const tags=[];(d.canonical||[]).forEach(x=>tags.push(`<span class="tag blue">${esc(x.rule||'R')} · ${esc(x.selection_ru||x.selection||'')} ${x.paper_user_execution_odds?`@${esc(x.paper_user_execution_odds)}`:''}</span>`));(d.watch||[]).forEach(x=>tags.push(`<span class="tag orange">WATCH · ${esc(x.selection_ru||x.selection||x.watch_family||'')}</span>`));html+=section('Статус',`<div class="detail-tags">${tags.join('')||'<span class="tag">Нет R/WATCH сигнала</span>'}</div>`);
  const marketRows=currentMarketRows(d);html+=section('Текущий обзор рынков',marketRows.length?`<div class="market-list">${marketRows.map(x=>`<div class="market-row">${esc(x)}</div>`).join('')}</div><div class="market-note">Рынки ≠ сигналы. Выводятся только как market view.</div>`:'<div class="empty">Рынки пока не собраны.</div>');
  const c=first(d.context);if(c){const pairs=cleanPairs(c,[['Стадион','venue_name'],['Судья','referee'],['Отдых хозяев, ч','home_rest_hours'],['Отдых гостей, ч','away_rest_hours'],['След. матч хозяев, ч','home_next_match_hours'],['След. матч гостей, ч','away_next_match_hours'],['Snapshot','snapshot_type']]);html+=section('Контекст',pairs.length?pairGrid(pairs):'<div class="empty">Контекст есть, но компактных полей пока нет.</div>')}
  const life=d.lifecycle||[];html+=section('Lifecycle',life.length?`<div class="timeline">${life.slice(-20).map(x=>`<div class="timeline-item"><b>${esc(x.event_type||x.event||x.status||'EVENT')}</b><div>${esc(x.event_at_utc||x.event_time_utc||x.captured_at_utc||'')} ${x.details?`· ${esc(x.details)}`:''}</div></div>`).join('')}</div>`:'<div class="empty">Lifecycle для этого fixture пока пуст.</div>');
  if((d.settlements||[]).length)html+=section('Результат / settlement',pairGrid([['Settlement rows',d.settlements.length],['Последний статус',last(d.settlements)?.settlement_status||'—']]));
  $('#detail-body').innerHTML=html}

function renderPerformance(perf){const c=perf.canonical?.overall||{};const w=perf.watch?.overall||{};$('#stats-summary').innerHTML=[['R settled',c.settled_rows??0],['R P/L',fmtNum(c.user_profit_u,'u')],['WATCH settled',w.settled??0],['WATCH P/L',fmtNum(w.user_profit_u,'u')]].map(([k,v])=>`<div class="metric"><b>${esc(v)}</b><span>${esc(k)}</span></div>`).join('');
  $('#stats-canonical').innerHTML=`<div class="health-grid"><div class="health-item"><span>Всего forward</span><b>${esc(c.rows??0)}</b></div><div class="health-item"><span>Pending</span><b>${esc(c.pending_rows??0)}</b></div><div class="health-item"><span>W / L</span><b>${esc(c.wins??0)} / ${esc(c.losses??0)}</b></div><div class="health-item"><span>ROI</span><b>${esc(fmtNum(c.user_roi_pct,'%'))}</b></div><div class="health-item"><span>Execution coverage</span><b>${esc(fmtNum(c.user_execution_coverage_pct,'%'))}</b></div><div class="health-item"><span>Observed MDD</span><b>${esc(fmtNum(c.observed_user_max_drawdown_u,'u'))}</b></div></div><div class="market-note">Только clean prospective canonical forward. Historical backfill запрещён.</div>`;
  $('#stats-watch').innerHTML=`<div class="health-grid"><div class="health-item"><span>Crossings</span><b>${esc(w.crossings??0)}</b></div><div class="health-item"><span>Pending</span><b>${esc(w.pending??0)}</b></div><div class="health-item"><span>W / L</span><b>${esc(w.wins??0)} / ${esc(w.losses??0)}</b></div><div class="health-item"><span>ROI</span><b>${esc(fmtNum(w.user_roi_pct,'%'))}</b></div><div class="health-item"><span>Close persistence</span><b>${esc(fmtNum(w.close_persistence_pct,'%'))}</b></div><div class="health-item"><span>Observed MDD</span><b>${esc(fmtNum(w.observed_max_drawdown_u,'u'))}</b></div></div><div class="market-note">WATCH — research only. Не смешивается с canonical статистикой.</div>`;
  const p=perf.probability_module||{};$('#stats-probability').innerHTML=p.status==='NOT_VALIDATED_YET'?`<div class="empty"><b>Пока не активировано.</b><br>ПБК не будет придумывать проценты. После отдельной валидации здесь появятся два независимых рейтинга: <b>«Максимальная вероятность прохода»</b> и <b>«Лучший value»</b>.</div>`:`<div class="health-grid"><div class="health-item"><span>Макс. вероятность</span><b>активно</b></div><div class="health-item"><span>Лучший value</span><b>активно</b></div></div>`}

function readNotificationIds(){try{const raw=JSON.parse(localStorage.getItem(READ_NOTIFICATIONS_KEY)||'[]');return new Set(Array.isArray(raw)?raw:[])}catch{return new Set()}}
function writeNotificationIds(ids){try{localStorage.setItem(READ_NOTIFICATIONS_KEY,JSON.stringify([...ids].slice(-500)))}catch{}}
function fmtNotificationTime(v){if(!v)return '—';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)}
function notificationLabel(category){return ({SIGNAL:'R-сигнал',WATCH:'WATCH',LINEUP:'Составы',SETTLEMENT:'Результат',FIXTURE:'Матч',SYSTEM:'Система'})[category]||category||'Событие'}
function markNotificationRead(id){if(!id)return;const read=readNotificationIds();read.add(id);writeNotificationIds(read)}
function renderNotifications(payload=notificationPayload){notificationPayload=payload||{items:[],summary:{}};const all=notificationPayload.items||[];const read=readNotificationIds();const filter=$('#notification-filter')?.value||'';const visible=filter?all.filter(x=>x.category===filter):all;const unread=all.filter(x=>!read.has(x.id)).length;const badge=$('#notification-badge');if(badge){badge.textContent=String(unread);badge.hidden=unread===0}
  const summary=$('#notification-summary');if(summary){const categories=[['R',all.filter(x=>x.category==='SIGNAL').length],['WATCH',all.filter(x=>x.category==='WATCH').length],['Составы',all.filter(x=>x.category==='LINEUP').length],['Непрочитано',unread]];summary.innerHTML=categories.map(([k,v])=>`<div class="metric"><b>${esc(v)}</b><span>${esc(k)}</span></div>`).join('')}
  const list=$('#notifications-list');if(!list)return;list.innerHTML=visible.length?visible.map(x=>{const isRead=read.has(x.id);const fid=x.fixture_id?`data-fixture="${esc(x.fixture_id)}"`:'';return `<article class="notification-card ${esc(x.severity||'medium')} ${isRead?'read':'unread'}" data-notification-id="${esc(x.id)}" ${fid}><div class="notification-top"><span class="notification-kind">${esc(notificationLabel(x.category))}</span>${isRead?'':`<span class="notification-new">новое</span>`}</div><div class="notification-title">${esc(x.title||'Событие')}</div>${x.body?`<div class="notification-body">${esc(x.body)}</div>`:''}<div class="notification-meta">${esc(fmtNotificationTime(x.event_time_utc))}${x.league?` · ${esc(x.league)}`:''}${x.fixture_id?` · матч №${esc(x.fixture_id)}`:''}</div></article>`}).join(''):'<div class="empty">По этому фильтру уведомлений нет.</div>'}
function markAllNotificationsRead(){const read=readNotificationIds();for(const x of notificationPayload.items||[])read.add(x.id);writeNotificationIds(read);renderNotifications()}

async function openMatch(fid){if(!fid)return;const dlg=$('#match-dialog');$('#detail-title').textContent='Загрузка…';$('#detail-body').innerHTML='<div class="empty">Собираю карточку матча…</div>';dlg.showModal();try{const d=await api(`/v1/match?fixture_id=${encodeURIComponent(fid)}`);renderMatchDetail(d)}catch(e){$('#detail-body').innerHTML=`<div class="empty">Не удалось открыть матч: ${esc(e.message)}</div>`}}
function bindFixtureClicks(){document.addEventListener('click',e=>{const note=e.target.closest('[data-notification-id]');if(note){markNotificationRead(note.dataset.notificationId);renderNotifications()}const card=e.target.closest('[data-fixture]');if(card&&card.dataset.fixture)openMatch(card.dataset.fixture)})}

async function load(){try{const [attention,health,gov,perf,notifications]=await Promise.all([api('/v1/attention'),api('/v1/health'),api('/v1/governance').then(gov=>{challengers.update(gov);return gov}),api('/v1/performance'),api('/v1/notifications?limit=100')]);setHealthPill(health.system_health||health.status);const dataAge=applyFreshnessGuard(health,gov);const s=attention.summary||{};$('#summary-grid').innerHTML=[['R-сигналы',s.active_canonical??0],['WATCH',s.active_watch_crossings??0],['Ближайшие',s.nearest_monitored_rows??0],['Карточки',s.market_cards??0]].map(([k,v])=>`<div class="metric"><b>${esc(v)}</b><span>${esc(k)}</span></div>`).join('');$('#updated-at').textContent=attention.generated_at_local?`обновлено ${attention.generated_at_local.replace('T',' ').slice(0,16)}`:'';const attentionRows=[...(attention.red||[]),...(attention.orange||[])];setList('#attention-list',attentionRows);setList('#canonical-list',attention.canonical||[]);setList('#signals-list',attention.canonical||[]);setList('#watch-list',attention.watch||[]);const cards=attention.market_cards||[];setList('#today-market-cards',cards.slice(0,4),marketCard);setList('#all-market-cards',cards,marketCard);renderPerformance(perf);renderNotifications(notifications);const ex=gov.exposure||{};const promotion=gov.watch_promotion||{};$('#health-panel').innerHTML=`<div class="health-grid"><div class="health-item"><span>System Health</span><b>${esc(health.system_health||health.status||'—')}</b></div><div class="health-item"><span>Возраст Data Layer</span><b>${esc(dataAge===null?'—':`${Math.round(dataAge)} мин`)}</b></div><div class="health-item"><span>SQLite schema</span><b>v${esc(health.db_schema_version||'—')}</b></div><div class="health-item"><span>Canonical exposure</span><b>${esc(ex.logical_exposure_u??ex.total_logical_exposure_u??'—')}u</b></div><div class="health-item"><span>WATCH promotion</span><b>${esc(promotion.status||'governed')}</b></div><div class="health-item"><span>DB built UTC</span><b>${esc(health.db_built_at_utc||'—')}</b></div></div><div class="market-note">API read-only · интерфейс не меняет eligibility, ставки или правила.</div>`}catch(e){challengers.unavailable();setHealthPill('CRITICAL');setDataSafety('bad','API недоступен','Не удалось подтвердить актуальность ПБК. Старые данные нельзя использовать как текущие сигналы или коэффициенты.');$('#attention-list').innerHTML=`<div class="empty">Не удалось загрузить API: ${esc(e.message)}</div>`;console.error(e)}}

$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#view-${b.dataset.view}`).classList.add('active')}));
$('#notification-filter')?.addEventListener('change',()=>renderNotifications());$('#notifications-read-all')?.addEventListener('click',markAllNotificationsRead);
$('#detail-close').addEventListener('click',()=>$('#match-dialog').close());$('#match-dialog').addEventListener('click',e=>{if(e.target===$('#match-dialog'))$('#match-dialog').close()});bindFixtureClicks();
window.addEventListener('offline',()=>{challengers.unavailable();setDataSafety('bad','Нет связи','Приложение не может подтвердить свежесть данных. Не используй коэффициенты или сигналы до восстановления соединения.')});window.addEventListener('online',()=>load());
if('serviceWorker'in navigator){let refreshing=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(refreshing)return;refreshing=true;location.reload()});navigator.serviceWorker.register('/sw.js').then(reg=>{reg.update().catch(()=>{});setInterval(()=>reg.update().catch(()=>{}),15*60*1000)}).catch(()=>{})}
load();setInterval(load,60000);
