const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const api=async path=>{const r=await fetch(`/api${path}`,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmtOdds=v=>v===null||v===undefined||v===''?'—':String(v);
const cardClass=p=>({RED:'red',ORANGE:'orange',BLUE:'blue',GRAY:'gray'}[p]||'gray');

function signalCard(x){const odds=x.paper_user_odds??x.user_odds??'';const book=x.paper_user_book??x.user_book??'';return `<article class="card ${cardClass(x.priority)}"><div><div class="eyebrow">${esc(x.rule||x.stage||x.league||'')}</div><div class="teams">${esc(x.home_team)} — ${esc(x.away_team)}</div><div class="meta">${esc(x.league||'')} · ${esc(x.kickoff_local||'')} ${x.context?`· ${esc(x.context)}`:''}${x.reason?`· ${esc(x.reason)}`:''}</div></div><div class="pick"><div class="selection">${esc(x.selection||x.market||'')}</div>${odds?`<div class="odds">${esc(fmtOdds(odds))}${book?` @ ${esc(book)}`:''}</div>`:''}</div></article>`}

function marketCard(x){const rows=(x.markets||[]).map(m=>`<div class="market-row">${esc(m.text||m.market||'')}</div>`).join('');return `<article class="match-card"><div class="eyebrow">${esc(x.league||'')} · ${esc(x.kickoff_local||'')}</div><div class="match-title">${esc(x.home_team)} — ${esc(x.away_team)}</div><div class="match-meta">Матч №${esc(x.fixture_id||'')} · обзор рынка</div><div class="market-list">${rows||'<div class="empty">Рыночные строки пока не собраны.</div>'}</div><div class="market-note">MARKET VIEW ONLY — не сигнал и не рекомендация</div></article>`}

function setList(id,items,renderer=signalCard){const el=$(id);el.innerHTML=items?.length?items.map(renderer).join(''):'<div class="empty">Сейчас ничего нет.</div>'}
function setHealthPill(status){const el=$('#health-pill');el.classList.remove('ok','warn','bad');const s=String(status||'UNKNOWN').toUpperCase();el.classList.add(s==='HEALTHY'||s==='OK'?'ok':s==='WARN'?'warn':'bad');el.querySelector('span:last-child').textContent=s}

async function load(){try{const [attention,health,gov]=await Promise.all([api('/v1/attention'),api('/v1/health'),api('/v1/governance')]);setHealthPill(health.system_health||health.status);const s=attention.summary||{};$('#summary-grid').innerHTML=[['R-сигналы',s.active_canonical??0],['WATCH',s.active_watch_crossings??0],['Ближайшие',s.nearest_monitored_rows??0],['Карточки',s.market_cards??0]].map(([k,v])=>`<div class="metric"><b>${esc(v)}</b><span>${esc(k)}</span></div>`).join('');$('#updated-at').textContent=attention.generated_at_local?`обновлено ${attention.generated_at_local.replace('T',' ').slice(0,16)}`:'';const attentionRows=[...(attention.red||[]),...(attention.orange||[])];setList('#attention-list',attentionRows);setList('#canonical-list',attention.canonical||[]);setList('#signals-list',attention.canonical||[]);setList('#watch-list',attention.watch||[]);const cards=attention.market_cards||[];setList('#today-market-cards',cards.slice(0,4),marketCard);setList('#all-market-cards',cards,marketCard);const ex=gov.exposure||{};const promotion=gov.watch_promotion||{};$('#health-panel').innerHTML=`<div class="health-grid"><div class="health-item"><span>System Health</span><b>${esc(health.system_health||health.status||'—')}</b></div><div class="health-item"><span>SQLite schema</span><b>v${esc(health.db_schema_version||'—')}</b></div><div class="health-item"><span>Canonical exposure</span><b>${esc(ex.logical_exposure_u??ex.total_logical_exposure_u??'—')}u</b></div><div class="health-item"><span>WATCH promotion</span><b>${esc(promotion.status||'governed')}</b></div></div><div class="market-note">API read-only · интерфейс не меняет eligibility, ставки или правила.</div>`}catch(e){setHealthPill('CRITICAL');$('#attention-list').innerHTML=`<div class="empty">Не удалось загрузить API: ${esc(e.message)}</div>`;console.error(e)}}

$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#view-${b.dataset.view}`).classList.add('active')}));
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>{});
load();setInterval(load,60000);
