const pEsc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const pSel=s=>({Away:'П2',Home:'П1',Draw:'Х'})[s]||s||'—';
const pFmt=(v,d=2)=>v===null||v===undefined||v===''?'—':Number(v).toFixed(d);
const pApi=async()=>{const r=await fetch('/api/v1/performance',{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()};
const pMatchApi=async fid=>{const r=await fetch(`/api/v1/match?fixture_id=${encodeURIComponent(fid)}`,{headers:{Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()};

function probabilityCard(x,kind){if(!x)return '<div class="empty">Сейчас нет подходящего active R-сигнала.</div>';const title=kind==='prob'?'Максимальная вероятность':'Лучший value';const main=kind==='prob'?`${pFmt(x.p_pbk_pct)}%`:`${x.ev_pct===null||x.ev_pct===undefined?'—':(Number(x.ev_pct)>=0?'+':'')+pFmt(x.ev_pct)}% EV`;const sub=kind==='prob'?`рынок ${pFmt(x.p_market_pct)}%`:`ПБК ${pFmt(x.p_pbk_pct)}% · рынок ${pFmt(x.p_market_pct)}%`;return `<article class="prob-card ${kind}" data-fixture="${pEsc(x.api_fixture_id||'')}"><div class="prob-label">${pEsc(title)}</div><div class="prob-teams">${pEsc(x.home_team)} — ${pEsc(x.away_team)}</div><div class="prob-pick"><b>${pEsc(pSel(x.selection))}</b>${x.paper_user_odds?` <span>@${pEsc(x.paper_user_odds)} ${pEsc(x.paper_user_bookmaker||'')}</span>`:''}</div><div class="prob-main">${pEsc(main)}</div><div class="prob-sub">${pEsc(sub)} · ${pEsc(x.rule||'')}</div><div class="prob-open">Открыть карточку матча →</div></article>`}

function renderProbability(payload){const m=payload?.probability_module||{};const today=document.querySelector('#probability-today');const stats=document.querySelector('#probability-stats-detail');if(!today||!stats)return;if(m.status!=='ACTIVE_FORWARD_MONITORING'){today.innerHTML='<div class="empty">Probability-модуль пока не готов к live-ранжированию.</div>';stats.innerHTML='<div class="empty">Нет активной validated probability-модели.</div>';return}const byProb=m.max_probability||[];const byValue=m.best_value||[];today.innerHTML=probabilityCard(byProb[0],'prob')+probabilityCard(byValue[0],'value');const perf=m.forward_performance||{};const rules=perf.by_rule||{};const ruleRows=Object.entries(rules).map(([r,x])=>`<div class="prob-rule"><b>${pEsc(r)}</b><span>forward settled: ${pEsc(x.settled_predictions??0)} · Brier рынок ${pFmt(x.brier_market,4)} / ПБК ${pFmt(x.brier_pbk,4)} · log-loss рынок ${pFmt(x.logloss_market,4)} / ПБК ${pFmt(x.logloss_pbk,4)}</span></div>`).join('');const all=byProb.map(x=>`<div class="prob-rank-row" data-fixture="${pEsc(x.api_fixture_id||'')}"><b>#${pEsc(x.probability_rank)} ${pEsc(x.home_team)} — ${pEsc(x.away_team)}</b><span>${pEsc(pSel(x.selection))} · ПБК ${pFmt(x.p_pbk_pct)}% · EV ${x.ev_pct===null||x.ev_pct===undefined?'—':(Number(x.ev_pct)>=0?'+':'')+pFmt(x.ev_pct)}%</span></div>`).join('');stats.innerHTML=`<div class="prob-status"><b>Stage75 ${pEsc(m.status)}</b><span>модель ${pEsc(m.model_version||'—')} · canonical only · WATCH исключён · размер ставки не меняется</span></div>${all?`<div class="prob-ranks">${all}</div>`:'<div class="empty">Активных R сейчас нет.</div>'}${ruleRows?`<div class="prob-rules"><h3>Forward-калибровка</h3>${ruleRows}</div>`:''}<div class="market-note">Проценты ПБК — отдельная validated calibration поверх no-vig рынка. Они не создают новый сигнал и не являются доказательством реальной ставки.</div>`}

function percent(v,pct){if(pct!==null&&pct!==undefined&&pct!=='')return Number(pct);if(v===null||v===undefined||v==='')return null;return Number(v)*100}
function matchProbabilityHtml(x){const p=percent(x.p_pbk,x.p_pbk_pct);const m=percent(x.p_market_no_vig,x.p_market_pct);const ev=percent(x.ev,x.ev_pct);const evText=ev===null?'—':`${ev>=0?'+':''}${pFmt(ev)}%`;const odds=x.paper_user_odds??x.user_odds??'';const book=x.paper_user_bookmaker??x.user_bookmaker??'';return `<section class="detail-section" id="detail-probability"><h3>Вероятность / value ПБК</h3><div class="detail-grid"><div class="detail-row"><div class="eyebrow">Выбор</div><b>${pEsc(pSel(x.selection))}</b></div><div class="detail-row"><div class="eyebrow">Вероятность ПБК</div><b>${p===null?'—':pEsc(`${pFmt(p)}%`)}</b></div><div class="detail-row"><div class="eyebrow">Рынок no-vig</div><b>${m===null?'—':pEsc(`${pFmt(m)}%`)}</b></div><div class="detail-row"><div class="eyebrow">Расчётный EV</div><b>${pEsc(evText)}</b></div><div class="detail-row"><div class="eyebrow">Исполнимый коэффициент</div><b>${odds?pEsc(`${odds}${book?` @ ${book}`:''}`):'—'}</b></div><div class="detail-row"><div class="eyebrow">Статус модели</div><b>${pEsc(x.probability_status||'forward monitoring')}</b></div></div><div class="market-note">Stage75 только оценивает уже существующий canonical R-сигнал. Вероятность/value не создают новую ставку и не меняют размер позиции.</div></section>`}
async function injectMatchProbability(fid){try{const d=await pMatchApi(fid);const x=(d.probability?.active_rankings||[])[0]||(d.probability?.predictions||[])[0];if(!x)return;for(let n=0;n<25;n++){const body=document.querySelector('#detail-body');const dlg=document.querySelector('#match-dialog');if(body&&dlg?.open&&body.querySelector('.detail-section')){body.querySelector('#detail-probability')?.remove();const firstSection=body.querySelector('.detail-section');firstSection.insertAdjacentHTML('afterend',matchProbabilityHtml(x));return}await new Promise(r=>setTimeout(r,80))}}catch(e){console.debug('PBK probability detail unavailable',e)}}

document.addEventListener('click',e=>{const card=e.target.closest('[data-fixture]');const fid=card?.dataset?.fixture;if(fid)injectMatchProbability(fid)});
async function loadProbability(){try{renderProbability(await pApi())}catch(e){const today=document.querySelector('#probability-today');const stats=document.querySelector('#probability-stats-detail');if(today)today.innerHTML=`<div class="empty">Не удалось загрузить probability: ${pEsc(e.message)}</div>`;if(stats)stats.innerHTML='<div class="empty">Probability API недоступен.</div>'}}
loadProbability();setInterval(loadProbability,60000);
