import test from 'node:test';
import assert from 'node:assert/strict';
import {renderMatchCard,renderMatchCardLoading,renderMatchCardError,safeMediaUrl,matchCardHeading,matchCardCoverage} from '../match-card.js';

function base(overrides={}){
  const payload={
    fixture:{fixture_id:'999',league_name:'Premier League',country_flag_url:'https://img/flag.png',league_logo_url:'https://img/league.png',round:'Round 5',kickoff_utc:'2026-09-14T16:30:00Z',status:'scheduled',source_status:'NS',elapsed:null,score:null,home:{name:'Alpha',logo_url:'https://img/a.png',red_cards:0},away:{name:'Beta',logo_url:'https://img/b.png',red_cards:0},observed_at_utc:'2026-09-14T15:00:00Z',live_observed_at_utc:null,live_freshness_status:'fresh'},
    motivation:{available:false,no_lookahead:true,coverage:{status:'UNKNOWN',limitations:['NO_STANDINGS_SNAPSHOT']}},
    prediction:{available:false,items:[]},odds:{available:false,items:[]},context:{available:false},value_radar:{available:false,research_only:true,creates_signal:false,stake_changes:false,items:[]},canonical:{available:false,items:[]},coverage:{status:'PARTIAL',sections:{motivation:false,context:false,prediction:false,odds:false,value_radar:false,canonical:false},limitations:['MOTIVATION_UNAVAILABLE','ODDS_UNAVAILABLE']},read_only:true,provider_polling:false,eligibility_mutation:false,model_mutation:false,
  };
  return Object.assign(payload,overrides);
}

test('header renders names and scheduled kickoff without fake score',()=>{const html=renderMatchCard(base());assert.match(html,/Alpha/);assert.match(html,/Beta/);assert.match(html,/МСК/);assert.doesNotMatch(html,/>0:0</)});
test('safe media accepts https and rejects http',()=>{assert.equal(safeMediaUrl('https://a.test/x.png'),'https://a.test/x.png');assert.equal(safeMediaUrl('http://a.test/x.png'),'')});
test('unsafe media becomes placeholder',()=>{const p=base();p.fixture.home.logo_url='javascript:alert(1)';assert.match(renderMatchCard(p),/match-card-v2-image-placeholder/)});
test('LIVE score and elapsed render',()=>{const p=base();p.fixture.status='live';p.fixture.score={home:2,away:1};p.fixture.elapsed=67;const html=renderMatchCard(p);assert.match(html,/2:1/);assert.match(html,/LIVE/);assert.match(html,/67′/)});
test('red card one and two render',()=>{const p=base();p.fixture.home.red_cards=1;p.fixture.away.red_cards=2;const html=renderMatchCard(p);assert.match(html,/🟥/);assert.match(html,/🟥 2/)});
test('stale freshness is visible',()=>{const p=base();p.fixture.live_freshness_status='stale';assert.match(renderMatchCard(p),/Freshness: stale/)});
test('motivation available renders both teams and no-lookahead trust',()=>{const p=base();p.motivation={available:true,no_lookahead:true,standings_context:{snapshot_observed_at_utc:'2026-09-14T15:00:00Z',requested_as_of_utc:'2026-09-14T16:30:00Z'},home:{primary_context:'TITLE',pressure:'MEDIUM',season_phase:'LATE',reason_codes:['TITLE_GAP_2']},away:{primary_context:'SURVIVAL',pressure:'HIGH',reason_codes:['WITHIN_3_OF_SURVIVAL']}};const html=renderMatchCard(p);assert.match(html,/TITLE/);assert.match(html,/SURVIVAL/);assert.match(html,/без future leakage/)});
test('motivation unavailable is honest',()=>assert.match(renderMatchCard(base()),/Турнирная мотивация пока недоступна/));
test('probability and market probability are distinct and not best bet',()=>{const p=base();p.prediction={available:true,items:[{rule:'R1',selection:'Away',p_pbk:0.6748,p_market_no_vig:0.6045,model_version:'m1',status:'FROZEN_PREMATCH'}]};const html=renderMatchCard(p);assert.match(html,/Вероятность ПБК/);assert.match(html,/Рынок без маржи/);assert.doesNotMatch(html,/best bet/i)});
test('odds show bookmaker and timestamp',()=>{const p=base();p.odds={available:true,items:[{rule:'R1',selection:'Away',captured_at_utc:'2026-09-14T15:00:00Z',best_odds:'1.65',best_book:'Book X',user_best_odds:'1.62',user_best_book:'Marathonbet',bet365_odds:'1.60'}]};const html=renderMatchCard(p);assert.match(html,/1.65/);assert.match(html,/Book X/);assert.match(html,/Снимок/)});
test('context renders referee venue rest',()=>{const p=base();p.context={available:true,referee:'Ref A',venue:{name:'Stadium',city:'City'},rest_hours:{home:120,away:96},previous_fixture:{home:{},away:{}},next_fixture:{home:{},away:{}},lineups:{available:false},injuries:{total:0,home:0,away:0,items:[]}};const html=renderMatchCard(p);assert.match(html,/Ref A/);assert.match(html,/Stadium/);assert.match(html,/120 ч/)});
test('lineups unavailable state renders',()=>assert.match(renderMatchCard(base()),/Подтверждённые составы ещё не получены/));
test('lineup renders coach formation and xi',()=>{const p=base();p.context={available:true,venue:{},rest_hours:{},previous_fixture:{},next_fixture:{},injuries:{items:[]},lineups:{available:true,home_formation:'4-3-3',away_formation:'4-2-3-1',home_coach:'Coach H',away_coach:'Coach A',home_start_xi:[{player:{name:'H1'}}],away_start_xi:[{name:'A1'}]}};const html=renderMatchCard(p);assert.match(html,/Coach H/);assert.match(html,/4-3-3/);assert.match(html,/H1/);assert.match(html,/A1/)});
test('injury object never becomes object Object',()=>{const p=base();p.context={available:true,venue:{},rest_hours:{},previous_fixture:{},next_fixture:{},lineups:{available:false},injuries:{total:1,home:1,away:0,items:[{player:{name:'Player X'},reason:'Hamstring'}]}};const html=renderMatchCard(p);assert.match(html,/Player X/);assert.match(html,/Hamstring/);assert.doesNotMatch(html,/\[object Object\]/)});
test('Value Radar stays research-only and not canonical',()=>{const p=base();p.value_radar={available:true,research_only:true,creates_signal:false,stake_changes:false,items:[{radar_kind:'STRONG_VALUE',primary_rule:'R1',selection:'Away',p_pbk_pct:67,p_market_pct:60,edge_pp:7,ev_pct:8.5,executable_odds:1.62,executable_bookmaker:'Book',probability_status:'VALIDATED'}]};const html=renderMatchCard(p);assert.match(html,/Research only · не новый сигнал/);assert.match(html,/creates_signal=false/)});
test('canonical rows render and absence is explicit',()=>{assert.match(renderMatchCard(base()),/Canonical-сигнала по матчу нет/);const p=base();p.canonical={available:true,items:[{rule:'R1',selection:'Away',status:'PAPER',stake_u:'1.0',paper_user_execution_odds:'1.62',paper_user_execution_bookmaker:'Book'}]};assert.match(renderMatchCard(p),/1\.0u/)});
test('partial coverage and safety footer render',()=>{const p=base();const html=renderMatchCard(p);assert.equal(matchCardCoverage(p).status,'PARTIAL');assert.match(html,/Часть разделов недоступна/);assert.match(html,/Read-only/);assert.match(html,/без прямого provider polling/)});
test('HTML escapes untrusted text',()=>{const p=base();p.fixture.home.name='<script>x</script>';p.fixture.away.name='A&B';const html=renderMatchCard(p);assert.doesNotMatch(html,/<script>/);assert.match(html,/&lt;script&gt;/);assert.match(html,/A&amp;B/)});
test('missing optional sections do not throw',()=>assert.doesNotThrow(()=>renderMatchCard({fixture:{home:{},away:{}},coverage:{}})));
test('rendered markup has no direct provider endpoint',()=>assert.doesNotMatch(renderMatchCard(base()),/api-football|api-sports/i));
test('loading error and heading helpers are stable',()=>{assert.match(renderMatchCardLoading(),/Match Card v2/);assert.match(renderMatchCardError('<bad>'),/&lt;bad&gt;/);assert.equal(matchCardHeading(base()).title,'Alpha — Beta')});
