import test from 'node:test';
import assert from 'node:assert/strict';
import {renderMatchCard,renderMatchCardLoading,renderMatchCardError,safeMediaUrl,matchCardHeading,matchCardCoverage} from '../match-card.js';

function base(overrides={}){
  const payload={
    fixture:{fixture_id:'999',league_name:'Premier League',country_flag_url:'https://img/flag.png',league_logo_url:'https://img/league.png',round:'Round 5',kickoff_utc:'2026-09-14T16:30:00Z',status:'scheduled',source_status:'NS',elapsed:null,score:null,home:{name:'Alpha',logo_url:'https://img/a.png',red_cards:0},away:{name:'Beta',logo_url:'https://img/b.png',red_cards:0},observed_at_utc:'2026-09-14T15:00:00Z',live_observed_at_utc:null,live_freshness_status:'fresh'},
    motivation:{available:false,no_lookahead:true,coverage:{status:'UNKNOWN',limitations:['NO_STANDINGS_SNAPSHOT']}},
    prediction:{available:false,items:[]},
    markets:{available:false,pre_match_frozen:true,creates_signal:false,stake_changes:false,model_probability_created:false,user_line_policy:'NO_QUARTER_ASIAN_HANDICAPS',available_family_count:0,total_family_count:8,coverage_status:'UNKNOWN',families:[]},
    odds:{available:false,items:[]},context:{available:false},value_radar:{available:false,research_only:true,creates_signal:false,stake_changes:false,items:[]},canonical:{available:false,items:[]},coverage:{status:'PARTIAL',sections:{motivation:false,context:false,prediction:false,markets:false,odds:false,value_radar:false,canonical:false},limitations:['MOTIVATION_UNAVAILABLE','MARKETS_UNAVAILABLE','ODDS_UNAVAILABLE']},read_only:true,provider_polling:false,eligibility_mutation:false,model_mutation:false,
  };
  return Object.assign(payload,overrides);
}

function marketPayload(){
  const p=base();
  p.markets={available:true,pre_match_frozen:true,creates_signal:false,stake_changes:false,model_probability_created:false,user_line_policy:'NO_QUARTER_ASIAN_HANDICAPS',available_family_count:4,total_family_count:8,coverage_status:'PARTIAL',families:[
    {id:'MATCH_RESULT_1X2',label_ru:'Исход матча — П1 / Х / П2',available:true,scope:'CANONICAL_INPUT_OBSERVATION',research_only:false,observed_at_utc:'2026-09-14T15:00:00Z',source:'stage53_latest_screen',items:[{selection:'П1',best_odds:'2.15',best_book:'Book A',bet365_odds:'2.10',market_no_vig:0.45},{selection:'Х',bet365_odds:'3.40',market_no_vig:0.28},{selection:'П2',bet365_odds:'3.60',market_no_vig:0.27}],limitations:[]},
    {id:'DRAW_NO_BET',label_ru:'Фора 0 — Ф1(0) / Ф2(0)',available:true,scope:'PROSPECTIVE_DATA',research_only:true,observed_at_utc:'2026-09-14T15:06:00Z',source:'stage71g_dnb_snapshots',no_quarter_lines:true,items:[{selection:'Ф1(0)',line:'0',bet365_odds:'1.55',user_odds:'1.57',user_bookmaker:'Marathonbet',market_no_vig:0.61,movement_pp:0.02},{selection:'Ф2(0)',line:'0',bet365_odds:'2.40',market_no_vig:0.39}],limitations:[]},
    {id:'MATCH_TOTAL',label_ru:'Тотал матча — ТБ / ТМ',available:true,scope:'WATCH_RESEARCH',research_only:true,observed_at_utc:'2026-09-14T15:09:00Z',source:'stage62_ou_snapshots',items:[{selection:'ТБ(2.5)',line:'2.5',bet365_odds:'1.90',user_odds:'1.92',user_bookmaker:'Marathonbet',market_no_vig:0.506,movement_pp:0.026},{selection:'ТМ(2.5)',line:'2.5',bet365_odds:'1.95',market_no_vig:0.494}],limitations:[]},
    {id:'TEAM_TOTAL',label_ru:'Индивидуальные тоталы — ИТБ / ИТМ',available:true,scope:'PROSPECTIVE_DATA',research_only:true,observed_at_utc:'2026-09-14T15:10:00Z',source:'stage71c_team_total_snapshots',items:[{selection:'ИТБ',team_name:'Alpha',team_side:'H',line:'1.5',bet365_odds:'2.05',market_no_vig:0.46},{selection:'ИТМ',team_name:'Alpha',team_side:'H',line:'1.5',bet365_odds:'1.75',market_no_vig:0.54}],limitations:[]},
    {id:'ASIAN_HANDICAP',label_ru:'Азиатская фора',available:false,scope:'REFERENCE_ONLY',research_only:false,no_quarter_lines:true,items:[],limitations:['GENERAL_ASIAN_HANDICAP_NOT_EXPOSED','QUARTER_LINES_SUPPRESSED']},
    {id:'EUROPEAN_HANDICAP',label_ru:'Европейская фора 3-way',available:false,scope:'PROSPECTIVE_DATA',research_only:true,no_quarter_lines:true,items:[],limitations:['NO_PREMATCH_EUROPEAN_HANDICAP_SNAPSHOT']},
    {id:'DOUBLE_CHANCE',label_ru:'Двойной шанс — 1Х / Х2 / 12',available:false,scope:'PROSPECTIVE_DATA',research_only:true,items:[],limitations:['NO_PREMATCH_DOUBLE_CHANCE_SNAPSHOT']},
    {id:'BTTS',label_ru:'Обе забьют — Да / Нет',available:false,scope:'WATCH_RESEARCH',research_only:true,items:[],limitations:['NO_PREMATCH_BTTS_SNAPSHOT']},
  ]};
  p.coverage={status:'PARTIAL',sections:{motivation:false,context:false,prediction:false,markets:true,odds:false,value_radar:false,canonical:false},limitations:['MOTIVATION_UNAVAILABLE','ODDS_UNAVAILABLE']};
  return p;
}

test('header renders names and scheduled kickoff without fake score',()=>{const html=renderMatchCard(base());assert.match(html,/Alpha/);assert.match(html,/Beta/);assert.match(html,/МСК/);assert.doesNotMatch(html,/>0:0</)});
test('safe media accepts https and rejects http',()=>{assert.equal(safeMediaUrl('https://a.test/x.png'),'https://a.test/x.png');assert.equal(safeMediaUrl('http://a.test/x.png'),'')});
test('unsafe media becomes placeholder',()=>{const p=base();p.fixture.home.logo_url='javascript:alert(1)';assert.match(renderMatchCard(p),/match-card-v2-image-placeholder/)});
test('LIVE score and elapsed render',()=>{const p=base();p.fixture.status='live';p.fixture.score={home:2,away:1};p.fixture.elapsed=67;const html=renderMatchCard(p);assert.match(html,/2:1/);assert.match(html,/LIVE/);assert.match(html,/67′/)});
test('red card one and two render',()=>{const p=base();p.fixture.home.red_cards=1;p.fixture.away.red_cards=2;const html=renderMatchCard(p);assert.match(html,/🟥/);assert.match(html,/🟥 2/)});
test('stale freshness is visible',()=>{const p=base();p.fixture.live_freshness_status='stale';assert.match(renderMatchCard(p),/Freshness: stale/)});
test('motivation available renders both teams and no-lookahead trust',()=>{const p=base();p.motivation={available:true,no_lookahead:true,standings_context:{snapshot_observed_at_utc:'2026-09-14T15:00:00Z',requested_as_of_utc:'2026-09-14T16:30:00Z'},home:{primary_context:'TITLE',pressure:'MEDIUM',season_phase:'LATE',reason_codes:['TITLE_GAP_2']},away:{primary_context:'SURVIVAL',pressure:'HIGH',reason_codes:['WITHIN_3_OF_SURVIVAL']}};const html=renderMatchCard(p);assert.match(html,/TITLE/);assert.match(html,/SURVIVAL/);assert.match(html,/без future leakage/)});
test('motivation unavailable is honest',()=>assert.match(renderMatchCard(base()),/Турнирная мотивация пока недоступна/));
test('probability and market probability are distinct and not best bet',()=>{const p=marketPayload();p.prediction={available:true,items:[{rule:'R1',selection:'Away',market_family:'MATCH_RESULT_1X2',p_pbk:0.6748,p_market_no_vig:0.6045,model_version:'m1',status:'FROZEN_PREMATCH'}]};const html=renderMatchCard(p);assert.match(html,/Вероятность ПБК/);assert.match(html,/Рынок без маржи/);assert.match(html,/Рынки/);assert.match(html,/no-vig/);assert.doesNotMatch(html,/best bet/i)});
test('market board renders core observed families',()=>{const html=renderMatchCard(marketPayload());assert.match(html,/Исход матча/);assert.match(html,/Фора 0/);assert.match(html,/Тотал матча/);assert.match(html,/Индивидуальные тоталы/);assert.match(html,/Покрытие 4\/8/)});
test('market board keeps research-only semantics',()=>{const html=renderMatchCard(marketPayload());assert.match(html,/research/);assert.match(html,/creates_signal=false/);assert.match(html,/модель не изменяется/)});
test('unavailable market families are explicit',()=>{const html=renderMatchCard(marketPayload());assert.match(html,/Нет подтверждённого pre-match снимка/);assert.match(html,/Азиатская фора/);assert.match(html,/Двойной шанс/)});
test('quarter asian policy is visible and no quarter EH line is rendered',()=>{const html=renderMatchCard(marketPayload());assert.match(html,/Четвертные азиатские форы скрыты/);assert.doesNotMatch(html,/линия -0\.25/);assert.doesNotMatch(html,/линия 0\.75/)});
test('canonical odds section stays separate from market board',()=>{const p=marketPayload();p.odds={available:true,items:[{rule:'R1',selection:'Away',captured_at_utc:'2026-09-14T15:00:00Z',best_odds:'1.65',best_book:'Book X',user_best_odds:'1.62',user_best_book:'Marathonbet',bet365_odds:'1.60'}]};const html=renderMatchCard(p);assert.match(html,/Canonical odds \/ execution/);assert.match(html,/Этот блок относится только к canonical execution/);assert.match(html,/Рынки/)});
test('context renders referee venue rest',()=>{const p=base();p.context={available:true,referee:'Ref A',venue:{name:'Stadium',city:'City'},rest_hours:{home:120,away:96},previous_fixture:{home:{},away:{}},next_fixture:{home:{},away:{}},lineups:{available:false},injuries:{total:0,home:0,away:0,items:[]}};const html=renderMatchCard(p);assert.match(html,/Ref A/);assert.match(html,/Stadium/);assert.match(html,/120 ч/)});
test('context renders capture metadata and competition class',()=>{const p=base();p.context={available:true,captured_at_utc:'2026-09-14T15:00:00Z',snapshot_type:'T3',context_only:true,referee:'Ref',venue:{},rest_hours:{},previous_fixture:{home:{opponent:'Prev',date_utc:'2026-09-10T15:00:00Z',competition:'Cup',competition_class:'CUP'},away:{}},next_fixture:{home:{},away:{}},lineups:{available:false},injuries:{items:[]},notes:'context note'};const html=renderMatchCard(p);assert.match(html,/Context/);assert.match(html,/T3/);assert.match(html,/CUP/);assert.match(html,/context note/)});
test('lineups unavailable state renders',()=>assert.match(renderMatchCard(base()),/Подтверждённые составы ещё не получены/));
test('lineup renders coach formation and xi',()=>{const p=base();p.context={available:true,venue:{},rest_hours:{},previous_fixture:{},next_fixture:{},injuries:{items:[]},lineups:{available:true,home_formation:'4-3-3',away_formation:'4-2-3-1',home_coach:'Coach H',away_coach:'Coach A',home_start_xi:[{player:{name:'H1'}}],away_start_xi:[{name:'A1'}]}};const html=renderMatchCard(p);assert.match(html,/Coach H/);assert.match(html,/4-3-3/);assert.match(html,/H1/);assert.match(html,/A1/)});
test('injury object never becomes object Object',()=>{const p=base();p.context={available:true,venue:{},rest_hours:{},previous_fixture:{},next_fixture:{},lineups:{available:false},injuries:{total:1,home:1,away:0,items:[{player:{name:'Player X'},reason:'Hamstring'}]}};const html=renderMatchCard(p);assert.match(html,/Player X/);assert.match(html,/Hamstring/);assert.doesNotMatch(html,/\[object Object\]/)});
test('Value Radar stays research-only and not canonical',()=>{const p=base();p.value_radar={available:true,research_only:true,creates_signal:false,stake_changes:false,items:[{radar_kind:'STRONG_VALUE',primary_rule:'R1',selection:'Away',p_pbk_pct:67,p_market_pct:60,edge_pp:7,ev_pct:8.5,executable_odds:1.62,executable_bookmaker:'Book',probability_status:'VALIDATED'}]};const html=renderMatchCard(p);assert.match(html,/Research only · не новый сигнал/);assert.match(html,/creates_signal=false/)});
test('canonical rows render and absence is explicit',()=>{assert.match(renderMatchCard(base()),/Canonical-сигнала по матчу нет/);const p=base();p.canonical={available:true,items:[{rule:'R1',selection:'Away',status:'PAPER',stake_u:'1.0',paper_user_execution_odds:'1.62',paper_user_execution_bookmaker:'Book'}]};assert.match(renderMatchCard(p),/1\.0u/)});
test('partial coverage and safety footer render',()=>{const p=base();const html=renderMatchCard(p);assert.equal(matchCardCoverage(p).status,'PARTIAL');assert.match(html,/Часть разделов недоступна/);assert.match(html,/Рынки/);assert.match(html,/Read-only/);assert.match(html,/без прямого provider polling/)});
test('HTML escapes untrusted market text',()=>{const p=marketPayload();p.markets.families[0].items[0].best_book='<script>x</script>';p.markets.families[3].items[0].team_name='A&B';const html=renderMatchCard(p);assert.doesNotMatch(html,/<script>/);assert.match(html,/&lt;script&gt;/);assert.match(html,/A&amp;B/)});
test('missing optional sections do not throw',()=>assert.doesNotThrow(()=>renderMatchCard({fixture:{home:{},away:{}},coverage:{}})));
test('rendered markup has no direct provider endpoint',()=>assert.doesNotMatch(renderMatchCard(base()),/api-football|api-sports/i));
test('loading error and heading helpers are stable',()=>{assert.match(renderMatchCardLoading(),/Match Card v2/);assert.match(renderMatchCardError('<bad>'),/&lt;bad&gt;/);assert.equal(matchCardHeading(base()).title,'Alpha — Beta')});
